<a href="https://colab.research.google.com/github/pablex72/challenge-101-numpy-exercises-python/blob/main/101_NumPy_Exercises_for_Data_Analysis_(Python).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
import pandas as pd 

In [8]:
#2. How to create a 1D array?

arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
#3. How to create a boolean array?
np.full((3, 3), True, dtype=bool)
#> array([[ True,  True,  True],
#>        [ True,  True,  True],
#>        [ True,  True,  True]], dtype=bool)

# Alternate method:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [13]:
#4. How to extract items that satisfy a given condition from 1D array?

# Input
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Solution
print('arr % 2',arr % 2)
print('arr[arr % 2]',arr[arr % 2])
print('arr[arr % 2 == 1]',arr[arr % 2 == 1])
#> array([1, 3, 5, 7, 9])

arr % 2 [0 1 0 1 0 1 0 1 0 1]
arr[arr % 2] [0 1 0 1 0 1 0 1 0 1]
arr[arr % 2 == 1] [1 3 5 7 9]
