<a href="https://colab.research.google.com/github/pablex72/challenge-101-numpy-exercises-python/blob/main/101_NumPy_Exercises_for_Data_Analysis_(Python)%202.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd 

In [3]:
#2. How to create a 1D array?

arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
#3. How to create a boolean array?
np.full((3, 3), True, dtype=bool)
#> array([[ True,  True,  True],
#>        [ True,  True,  True],
#>        [ True,  True,  True]], dtype=bool)

# Alternate method:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [16]:
#4. How to extract items that satisfy a given condition from 1D array?

# Input
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr[arr % 2]

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [19]:
#5. How to replace items that satisfy a condition with another value in numpy array?
arr[arr % 2 == 1] = -1
arr


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [21]:
#6. How to replace items that satisfy a condition without affecting the original array?
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
out
#The condition to be checked
#The value to be returned when the condition is True
#The value to be returned when the condition is False

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [22]:
#7. How to reshape an array?
arr = np.arange(10)
arr.reshape(2, -1)  # Setting to -1 automatically decides the number of cols
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9]])

#The first argument of reshape() method is the number of rows that the new array should have. In this case, it is 2.
#When -1 is used for the number of columns, numpy automatically calculates the number of columns such that the number of elements in the original array remains the same.

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])