<a href="https://colab.research.google.com/github/pablex72/challenge-101-numpy-exercises-python/blob/main/challenge_16_20_numpy_exercise_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

16. Swap columns 1 and 2 in the array arr.

In [3]:
import numpy as np

In [7]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

17. Swap rows 1 and 2 in the array arr:

In [17]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
arr[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

18. Reverse the rows of a 2D array arr.

In [20]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

19. Reverse the columns of a 2D array arr.

In [22]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

20. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

In [24]:
arr = np.arange(9).reshape(3,3)


In [25]:
rand_arr = np.random.uniform(5,10, size=(5,3))
