<a href="https://colab.research.google.com/github/pablex72/challenge-101-numpy-exercises-python/blob/main/challenge_21_25_numpy_exercise_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

21. Print or show only 3 decimal places of the numpy array rand_arr.

In [2]:
import numpy as np

In [5]:
rand_arr = np.random.random((5,3))
rand_arr

array([[0.77548459, 0.14916122, 0.63793406],
       [0.08661659, 0.18228075, 0.87780198],
       [0.11196839, 0.86106431, 0.0286992 ],
       [0.52820924, 0.05927032, 0.06872222],
       [0.10980769, 0.91736132, 0.25010075]])

In [22]:
np.set_printoptions(precision=3)
rand_arr[:5]

array([[0.775, 0.149, 0.638],
       [0.087, 0.182, 0.878],
       [0.112, 0.861, 0.029],
       [0.528, 0.059, 0.069],
       [0.11 , 0.917, 0.25 ]])

22. Pretty print rand_arr by suppressing the scientific notation (like 1e10)

In [23]:
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr

array([[5.434e-04, 2.784e-04, 4.245e-04],
       [8.448e-04, 4.719e-06, 1.216e-04],
       [6.707e-04, 8.259e-04, 1.367e-04]])

In [24]:
np.set_printoptions(suppress=True, precision=6)  
rand_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

23. Limit the number of items printed in python numpy array a to a maximum of 6 elements.


In [25]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

24. Print the full numpy array a without truncating.


In [26]:
np.set_printoptions(threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

25. Import the iris dataset keeping the text intact.


In [28]:
# Solution
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Print the first 3 rows
iris[:3]


array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)