<a href="https://colab.research.google.com/github/pablex72/challenge-101-numpy-exercises-python/blob/main/challenge_10_15_numpy_exercise_ML_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

10. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

In [3]:
import numpy as np
a = np.array([1,2,3])


In [11]:
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

11. Get the common items between a and b

In [12]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [14]:
np.intersect1d(a,b)

array([2, 4])

12. From array a remove all items present in array b

In [18]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [19]:
np.setdiff1d(a,b)

array([1, 2, 3, 4])

13. Get the positions where elements of a and b match



In [20]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [21]:
np.where(a==b)

(array([1, 3, 5, 7]),)

14. Get all items between 5 and 10 from a

In [22]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [24]:
index = np.where((a >= 5) & (a <= 10))
a[index]

array([ 6,  9, 10])

15. Convert the function maxx that works on two scalars, to work on two arrays.



In [25]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)

5

In [26]:
pair_max = np.vectorize(maxx, otypes=[float])

In [27]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

In [28]:
pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])